import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Plus, Edit, Trash2, Search, Filter } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import { db } from '../../services/firebase';
import { collection, query, where, onSnapshot, doc, deleteDoc } from 'firebase/firestore';

const SellerProducts = () => {
    const navigate = useNavigate();
    const { currentUser } = useAuth();
    const [products, setProducts] = useState([]);
    const [loading, setLoading] = useState(true);
    const [searchTerm, setSearchTerm] = useState('');

    useEffect(() => {
        if (!currentUser) {
            setProducts([]);
            setLoading(false);
            return;
        }

        // Fetch products where the sellerId matches the current user's UID
        const productsRef = collection(db, 'products');
        const q = query(productsRef, where('sellerId', '==', currentUser.uid));

        const unsubscribe = onSnapshot(
            q,
            (snapshot) => {
                const items = snapshot.docs.map((docSnap) => ({
                    id: docSnap.id, // UUID generated by Firebase
                    ...docSnap.data()
                }));
                setProducts(items);
                setLoading(false);
            },
            (error) => {
                console.error("Error fetching products:", error);
                setLoading(false);
            }
        );

        return unsubscribe;
    }, [currentUser]);

    const handleDelete = async (id) => {
        if (!currentUser) return;
        if (window.confirm('Are you sure you want to delete this product? This action cannot be undone.')) {
            try {
                const ref = doc(db, 'products', id);
                await deleteDoc(ref);
            } catch (error) {
                console.error("Error deleting product:", error);
                alert("Failed to delete product.");
            }
        }
    };

    const handleEdit = (id) => {
        // Future implementation: Navigate to edit page
        // navigate(`/seller/products/edit/${id}`);
        alert("Edit feature integration in progress.");
    };

    const filteredProducts = products.filter(product =>
        (product.name?.toLowerCase() || '').includes(searchTerm.toLowerCase()) ||
        (product.category?.toLowerCase() || '').includes(searchTerm.toLowerCase()) ||
        (product.id?.toLowerCase() || '').includes(searchTerm.toLowerCase())
    );

    if (loading) {
        return <div className="p-8 text-center text-gray-500">Loading your inventory...</div>;
    }

    return (
        <div className="p-6">
            <div className="flex justify-between items-center mb-6">
                <div>
                    <h1 className="text-2xl font-bold text-gray-800">Product Inventory</h1>
                    <p className="text-sm text-gray-500">Manage your store's listings and stock</p>
                </div>
                <button
                    onClick={() => navigate('/seller/products/new')}
                    className="bg-primary-600 hover:bg-primary-700 text-white px-4 py-2 rounded-lg flex items-center gap-2 transition-colors shadow-sm"
                >
                    <Plus className="w-5 h-5" />
                    Add New Product
                </button>
            </div>

            {/* Filters and Search */}
            <div className="bg-white p-4 rounded-lg border border-gray-200 shadow-sm mb-6 flex gap-4">
                <div className="flex-1 relative">
                    <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" />
                    <input
                        type="text"
                        placeholder="Search by name, category, or UUID..."
                        className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent outline-none transition-all"
                        value={searchTerm}
                        onChange={(e) => setSearchTerm(e.target.value)}
                    />
                </div>
                <button className="px-4 py-2 border border-gray-300 rounded-lg flex items-center gap-2 hover:bg-gray-50 text-gray-700">
                    <Filter className="w-5 h-5" />
                    Filter
                </button>
            </div>

            {/* Products Table */}
            <div className="bg-white rounded-lg border border-gray-200 shadow-sm overflow-hidden">
                <div className="overflow-x-auto">
                    <table className="w-full text-left border-collapse">
                        <thead className="bg-gray-50 border-b border-gray-200">
                            <tr>
                                <th className="px-6 py-3 text-xs font-bold text-gray-500 uppercase tracking-wider">UUID (Product ID)</th>
                                <th className="px-6 py-3 text-xs font-bold text-gray-500 uppercase tracking-wider">Image</th>
                                <th className="px-6 py-3 text-xs font-bold text-gray-500 uppercase tracking-wider">Name</th>
                                <th className="px-6 py-3 text-xs font-bold text-gray-500 uppercase tracking-wider">Seller ID</th>
                                <th className="px-6 py-3 text-xs font-bold text-gray-500 uppercase tracking-wider">Category</th>
                                <th className="px-6 py-3 text-xs font-bold text-gray-500 uppercase tracking-wider">Price Details</th>
                                <th className="px-6 py-3 text-xs font-bold text-gray-500 uppercase tracking-wider">Stock</th>
                                <th className="px-6 py-3 text-xs font-bold text-gray-500 uppercase tracking-wider">Description</th>
                                <th className="px-6 py-3 text-xs font-bold text-gray-500 uppercase tracking-wider text-right">Actions</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-gray-200">
                            {filteredProducts.map((product) => (
                                <tr key={product.id} className="hover:bg-gray-50 transition-colors">
                                    {/* UUID */}
                                    <td className="px-6 py-4 whitespace-nowrap text-xs font-mono text-gray-500 max-w-[120px] truncate" title={product.id}>
                                        {product.id}
                                    </td>

                                    {/* Image */}
                                    <td className="px-6 py-4 whitespace-nowrap">
                                        <div className="h-12 w-12 flex-shrink-0 bg-gray-100 rounded-lg overflow-hidden border border-gray-200">
                                            {product.image ? (
                                                <img className="h-full w-full object-cover type" src={product.image} alt={product.name} />
                                            ) : (
                                                <div className="h-full w-full flex items-center justify-center text-xs text-gray-400">No Img</div>
                                            )}
                                        </div>
                                    </td>

                                    {/* Name */}
                                    <td className="px-6 py-4 whitespace-nowrap">
                                        <div className="text-sm font-bold text-gray-900">{product.name}</div>
                                    </td>

                                    {/* Seller ID */}
                                    <td className="px-6 py-4 whitespace-nowrap text-xs font-mono text-gray-500 max-w-[120px] truncate" title={product.sellerId}>
                                        {product.sellerId}
                                    </td>

                                    {/* Category */}
                                    <td className="px-6 py-4 whitespace-nowrap">
                                        <span className="px-2.5 py-0.5 inline-flex text-xs leading-5 font-semibold rounded-full bg-primary-50 text-primary-700 border border-primary-100">
                                            {product.category}
                                        </span>
                                    </td>

                                    {/* Price */}
                                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900 font-medium">
                                        ${product.price ? Number(product.price).toFixed(2) : '0.00'}
                                    </td>

                                    {/* Stock */}
                                    <td className="px-6 py-4 whitespace-nowrap">
                                        <div className={`text-sm font-bold ${product.stock < 10 ? 'text-orange-600' : 'text-gray-700'}`}>
                                            {product.stock || 0}
                                        </div>
                                    </td>

                                    {/* Description */}
                                    <td className="px-6 py-4 text-sm text-gray-500 max-w-[200px]">
                                        <p className="truncate" title={product.description}>
                                            {product.description || 'No description provided.'}
                                        </p>
                                    </td>

                                    {/* Actions */}
                                    <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                        <div className="flex items-center justify-end gap-2">
                                            <button
                                                onClick={() => handleEdit(product.id)}
                                                className="p-1.5 text-primary-600 hover:bg-primary-50 rounded-lg transition-colors"
                                                title="Edit Product"
                                            >
                                                <Edit className="w-4 h-4" />
                                            </button>
                                            <button
                                                onClick={() => handleDelete(product.id)}
                                                className="p-1.5 text-red-600 hover:bg-red-50 rounded-lg transition-colors"
                                                title="Delete Product"
                                            >
                                                <Trash2 className="w-4 h-4" />
                                            </button>
                                        </div>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
                {filteredProducts.length === 0 && (
                    <div className="p-16 text-center">
                        <div className="bg-gray-50 rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4">
                            <Search className="w-8 h-8 text-gray-400" />
                        </div>
                        <h3 className="text-lg font-medium text-gray-900">No products found</h3>
                        <p className="text-gray-500 mt-1">Try adjusting your search or add a new product to your inventory.</p>
                    </div>
                )}
            </div>
        </div>
    );
};

export default SellerProducts;
